name: "Publish to PyPi"

on:
  push:
    tags:
      # SemVer tags
      - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Publish package
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: 3.9
          pypi_token: ${{ secrets.PYPI_TOKEN }}

